### ISSUE TITLE
Onion services

### ISSUE THREAD

**Issue by sneurlax** [Foundation-Devices/tor#15]
See https://gitlab.torproject.org/tpo/core/arti/-/blob/main/README.md#hidden-service-onion-service-client-support:

> Arti has support for connecting to Onion Services aka Tor Hidden Services.  However, currently it is disabled by default.
>
> In the meantime, if you would like to try it out, you can enable it on the command line (`cargo run -p arti -o address_filter.allow_onion_addrs=true proxy`). or edit your config file (set `allow_onion_addrs = true` in the section `[address_filter]`)

Otherwise, the old MagicalBitcoin/libtor-sys based package did support onion services safely, so either waiting for arti or regressing to libtor-sys could enable onion services

**Comment by sneurlax** [comment]
Thanks for the code showing how to enable it!  Feel free to merge that and close this issue.

We will probably wait to see if 1.1.9 or another later version enables onion services by default.  1.1.7 nor 1.1.8 brought guard discovery mitigations.  While these attacks would be rare, re:

> as long as the app it is embedded in is not attacking the user (or has other vectors not in the app's control, like a browser) we should be good with enabling this.

I'm not sure they'd require clientside collusion.  But regardless, the decision isn't mine or I'd vote for a regression to MagicalBitcoin/libtor-sys!  Better safe than sorry, folks :)

**Comment by sethforprivacy** [comment]
> Thanks for the code showing how to enable it! Feel free to merge that and close this issue.
> 
> We will probably wait to see if 1.1.9 or another later version enables onion services by default. 1.1.7 nor 1.1.8 brought guard discovery mitigations. While these attacks would be rare, re:
> 
> > as long as the app it is embedded in is not attacking the user (or has other vectors not in the app's control, like a browser) we should be good with enabling this.
> 
> I'm not sure they'd require clientside collusion. But regardless, the decision isn't mine or I'd vote for a regression to MagicalBitcoin/libtor-sys! Better safe than sorry, folks :)

One note here: from my understanding this attack is only possible if the motivated attacker specifically knows and targets your hidden service, which for personal nodes wouldn't normally even be published, much less well known.

The attack isn't feasible without knowing this Onion address as the attacker has to be able to Sybil and become two malicious nodes in the path. This seems to only be applicable to well-known hidden services that are at risk of targeted attack. If your use-case intends for users to use your own well-known Onion address for Fulcrum etc. then I would consider this more of a risk, but we don't have that specific use-case here at Foundation as this usage would only be for users personal nodes by design.
